language: ruby
rvm:
- 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: bearden.io
before_install:
  - openssl aes-256-cbc -K $encrypted_224b9241de42_key -iv $encrypted_224b9241de42_iv -in .travis.enc -out /tmp/travis_rsa -d
  - mkdir .asset-cache
script:
  - jekyll build
  - htmlproofer _site --check-favicon --check-html --allow-hash-href --only-4xx
before_deploy:
  - eval $(ssh-agent -s)
  - chmod 600 /tmp/travis_rsa
  - ssh-add /tmp/travis_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -vha --delete-after _dist/ deploy@bearden.io:live
  on:
    branch: master
