launguage: ruby
rvm:
  - 2.5
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: bearden.io
before_install:
  - openssl aes-256-cbc -K $encrypted_dfe163a3efc6_key -iv $encrypted_dfe163a3efc6_iv -in .travis_rsa.enc -out /tmp/travis_rsa -d
  - mkdir .asset-cache
script:
  - jekyll build
  - htmlproofer _dist --check-html --only-4xx --check-favicon
before_deploy:
  - eval $(ssh-agent -s)
  - chmod 600 /tmp/travis_rsa
  - ssh-add /tmp/travis_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -vha --delete-after _dist/ travis@bearden.io:bearden.io
  on:
    branch: master
