# configuration

## site info
title: Jacob Bearden
description: Software Developer
url: https://bearden.io

## compile settings
destination: _dist

### plugins
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-sitemap

### default layouts
defaults:
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post

### blog url
permalink: /blog/:title/

### markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

### assets
assets:
  source_maps: false
  compression: true
  sources:
    - _assets/css
    - _assets/js
    - _assets/font
    - _assets/img

### exclude files
exclude: [
  readme.md,
  Gemfile,
  Gemfile.lock,
  vendor,
  id_rsa.enc
]
