# configuration

## site info
title: Jacob Bearden
description: Software Developer
url: https://bearden.io

## compile settings
destination: _dist

### plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

### default layouts
defaults:
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post

### blog url
permalink: /blog/:title/

### markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

### assets
sass:
  style: compressed

### exclude files
exclude: [
  readme.md,
  Gemfile,
  Gemfile.lock,
  vendor
]
