# config
title: Jacob Bearden
description: Developer, Designer

gems:
  - jekyll-sitemap

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      type: "posts"
    values:
      layout: "post"

compress_html:
  clippings: all

sass:
  style:    compressed
  sass_dir: /_lib/sass

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include: [
  '_pages'
]
exclude: [
  'README.md',
  'CNAME',
  'LICENSE',
  'Gemfile'
]
