name: Build and Publish to Azure
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: azure login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: jekyll build
      uses: docker://faph/action-jekyll:1.5
      with:
        destination_dir: _dist
        add_nojekyll_tag: false
    
    - name: test build
      run: |
        bundle exec htmlproofer _dist --check-html --only-4xx --check-favicon
    
    - name: azure publish
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -s $GITHUB_WORKSPACE/_dist -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }}
