name: workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install
        run: |
          gem install bundler
          bundle install

      - name: Build
        run: |
          bundle exec jekyll build

      - name: Test
        run: |
          bundle exec htmlproofer _dist --only-4xx --allow-missing-href
